/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-15 20:11:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Proyecto integrador |GRUPO 5</title>\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"shortcut icon\"\r\n");
      out.write("      href=\"./assets/img/favicon.ico\"\r\n");
      out.write("      type=\"image/x-icon\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/estilos.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <!-- LA CONFERENCIA -->\r\n");
      out.write("    <section id=\"conferencia\" class=\"section_conferencia\">\r\n");
      out.write("      <h1>Conf Bs As</h1>\r\n");
      out.write("      <p>\r\n");
      out.write("        Bs As llega por primera vez a Argentina. Un evento para compartir con\r\n");
      out.write("        nuestra comunidad el conocimiento y expericencia de los expertos que\r\n");
      out.write("        están creando el futuro de Internet. Ven a conocer a miembros del\r\n");
      out.write("        evento, a otros estudiantes de Codo a Codo y a los oradores de primer\r\n");
      out.write("        nivel que tenemos para ti. Te esperamos!\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"section_conferencia_button\">\r\n");
      out.write("        <a class=\"quiero_ser_orador\" href=\"#formularioOrador\"\r\n");
      out.write("          >Quiero ser Orador</a\r\n");
      out.write("        >\r\n");
      out.write("        <a class=\"comprar_tickets\" href=\"tickets.jsp\"\r\n");
      out.write("          >Comprar tickets</a\r\n");
      out.write("        >\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- LOS ORADORES -->\r\n");
      out.write("    <main>\r\n");
      out.write("      <section id=\"oradores\" class=\"oradores\">\r\n");
      out.write("        <div class=\"titulo-subtitulo\">\r\n");
      out.write("          <h2 class=\"subtitulo\">CONOCE A LOS</h2>\r\n");
      out.write("          <h1 class=\"titulo\">ORADORES</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contenedor-tarjetas\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"./assets/img/steve.jpg\"\r\n");
      out.write("              class=\"card-img-top\"\r\n");
      out.write("              alt=\"imagen de Steve Jobs mostrando un celular\"\r\n");
      out.write("            />\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"temas\">\r\n");
      out.write("                <h6 class=\"colorAmarillo\">JavaScript</h6>\r\n");
      out.write("                <h6 class=\"colorCeleste\">React Native</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"card-title\">Steve Jobs</h5>\r\n");
      out.write("              <p class=\"card-text\">\r\n");
      out.write("                Destacado informático y empresario estadounidense. Creador del\r\n");
      out.write("                primer ordenador personal y fundador de Apple Computer, una\r\n");
      out.write("                empresa innovadora en el sector de la informática. Se\r\n");
      out.write("                caracteriza por tener ideas visionarias en el campo de los\r\n");
      out.write("                ordenadores personales, la telefonía móvil y la música digital.\r\n");
      out.write("                Así, revolucionó el sector durante más de tres décadas a través\r\n");
      out.write("                de sus productos.\r\n");
      out.write("              </p>\r\n");
      out.write("              <!-- <a href=\"#\" class=\"btn btn-primary\">Go somewhere</a> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"./assets/img/bill.jpg\"\r\n");
      out.write("              class=\"card-img-top\"\r\n");
      out.write("              alt=\"Imagen de Bill Gates tomandose las manos\"\r\n");
      out.write("            />\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"temas\">\r\n");
      out.write("                <h6 class=\"colorAmarillo\">Sistemas Operativos</h6>\r\n");
      out.write("                <h6 class=\"colorCeleste\">C ++</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"card-title\">Bill Gates</h5>\r\n");
      out.write("              <p class=\"card-text\">\r\n");
      out.write("                (William Henry Gates III; Seattle, Washington, 1955) Informático\r\n");
      out.write("                y empresario estadounidense, fundador de Microsoft. La fortuna\r\n");
      out.write("                de este precoz programador, que no llegó a terminar sus estudios\r\n");
      out.write("                y que a los 31 años era ya multimillonario, procede del éxito\r\n");
      out.write("                arrollador de su sistema operativo, el MS-DOS (1981), que\r\n");
      out.write("                evolucionaría hasta convertirse en el popular Windows 3.1 (1992)\r\n");
      out.write("              </p>\r\n");
      out.write("              <!-- <a href=\"#\" class=\"btn btn-primary\">Go somewhere</a> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"./assets/img/ada.jpeg\"\r\n");
      out.write("              class=\"card-img-top\"\r\n");
      out.write("              alt=\"Retrato en blanco y negro de Adda Lovelace\"\r\n");
      out.write("            />\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"temas\">\r\n");
      out.write("                <h6 class=\"colorGris\">Algoritmos</h6>\r\n");
      out.write("                <h6 class=\"colorRojo\">Cobol</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"card-title\">Adda Lovelace</h5>\r\n");
      out.write("              <p class=\"card-text\">\r\n");
      out.write("                Apasionada de las matemáticas que se animó a explorar el\r\n");
      out.write("                pensamiento abstracto mucho más allá de lo que “era aconsejable”\r\n");
      out.write("                para las mujeres. Su pasión y esmero dio resultados: creó lo que\r\n");
      out.write("                hoy se conoce como el primer algoritmo pensado para ser\r\n");
      out.write("                procesado por una máquina. De ahí que se la considera la primera\r\n");
      out.write("                programadora de computadoras.\r\n");
      out.write("              </p>\r\n");
      out.write("              <!-- <a href=\"#\" class=\"btn btn-primary\">Go somewhere</a> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          </section>\r\n");
      out.write("		    <section class=\"container mb-4 text-center\" id=\"restoOradores\">\r\n");
      out.write("		       <a class=\"btn btn-outline-success\" href=\"");
      out.print(request.getContextPath());
      out.write("/FindAllOradorController\">Conoce al resto de los ORADORES</a>\r\n");
      out.write("		    </section>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("   \r\n");
      out.write("      <section id=\"lugarFecha\" class=\"lugar_fecha\">\r\n");
      out.write("        <div class=\"lugar_fecha_imagen\">\r\n");
      out.write("          <img src=\"./assets/img/honolulu.jpg\" alt=\"Honolulu\" loading=\"lazy\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"lugar_fecha_texto\">\r\n");
      out.write("          <h2>Buenos Aires - Octubre</h2>\r\n");
      out.write("          <p>\r\n");
      out.write("            Buenos Aires es la provincia y localidad más grande del estado de\r\n");
      out.write("            Argentina, en los Estados Unidos. Honolulu el la más sureña de entre\r\n");
      out.write("            las principales ciudades estadounidenses. Aunque el nombre de\r\n");
      out.write("            Honolulu se refiere al área urbana en la costa sureste de las isla\r\n");
      out.write("            de Oahu, la ciudad y el condado de Honolulu han formado una ciudad-\r\n");
      out.write("            condado consolidada que cubre toda la ciduad (aproximadamente 600km2\r\n");
      out.write("            de superficie).\r\n");
      out.write("          </p>\r\n");
      out.write("          <a class=\"lugar_fecha_conoce_mas\" href=\"./pages/404.html\"\r\n");
      out.write("            >Conocé más</a\r\n");
      out.write("          >\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("     <section class=\"container\" id=\"form-orador\">\r\n");
      out.write("		        <div class=\"row justify-content-center\">\r\n");
      out.write("		            <div class=\"col-lg-8 col-xl-7\">\r\n");
      out.write("		                <h2 class=\"titulo-gral\">Conviértete en un <span>orador</span></h2>\r\n");
      out.write("		                <p class=\"text-center\">Anótate como orador para dar una charla ignite. Cuéntanos de qué quieres hablar!</p>\r\n");
      out.write("		                <form action=\"");
      out.print(request.getContextPath());
      out.write("/CreateOradorController\" method=\"POST\">\r\n");
      out.write("		                    <div class=\"row gx-2\">\r\n");
      out.write("		                        <div class=\"col-md mb-3\">\r\n");
      out.write("		                            <input type=\"text\" class=\"form-control\" name=\"nombre\" placeholder=\"Nombre\" aria-label=\"Nombre\" required>\r\n");
      out.write("		                        </div>\r\n");
      out.write("		                        <div class=\"col-md mb-3\">\r\n");
      out.write("		                            <input type=\"text\" class=\"form-control\" name=\"apellido\" placeholder=\"Apellido\" aria-label=\"Apellido\" required>\r\n");
      out.write("		                        </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"row\">\r\n");
      out.write("		                        <div class=\"col mb-3\">\r\n");
      out.write("		                            <input type=\"email\" class=\"form-control\" name=\"mail\" placeholder=\"Email\" aria-label=\"Email\" required>\r\n");
      out.write("		                        </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"row\">\r\n");
      out.write("		                        <div class=\"col mb-3\">\r\n");
      out.write("		                            <textarea class=\"form-control\" name=\"tema\" id=\"exampleFormControlTextarea1\" rows=\"4\"\r\n");
      out.write("		                                placeholder=\"Sobre qué quieres hablar?\" required></textarea>\r\n");
      out.write("		                            <div id=\"emailHelp\" class=\"form-text mb-3\">Recuerda incluir un título para tu charla.</div>\r\n");
      out.write("		                            <div class=\"d-grid\">\r\n");
      out.write("		                                <button type=\"submit\" class=\"btn btn-lg btn-form\">Enviar</button>\r\n");
      out.write("		                            </div>\r\n");
      out.write("		                        </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                </form>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		    </section>\r\n");
      out.write("		\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("  <script src=\"./js/menu.js\"></script>\r\n");
      out.write("  <script\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("    crossorigin=\"anonymous\"\r\n");
      out.write("  ></script>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
